apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "accenture-poc-svc"
  annotations:
    sonarqube.org/project-key: poc-backstage-svc
  links:
    - url: http://localhost:9000/dashboard?id=poc-backstage-svc
      title: Sonar Dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: experimental

