apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "accenture-poc-svc"
  annotations:
    sonarqube.org/project-key: poc-backstage-svc
    backstage.io/definition-at-location: 'url:https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/APIs/spotify.com/v1/swagger.yaml'
  links:
    - url: http://localhost:9000/dashboard?id=poc-backstage-svc
      title: Sonar Dashboard
      icon: sonarqube
spec:
  type: service
  owner: user:guest
  lifecycle: experimental

