apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "accenture-poc-svc"
  description: "accenture poc"
  dependsOn:
    - searcher
  tags:
    - java
    - node
  annotations:
    sonarqube.org/project-key: DoubleDdidi_poc-test-svc
    backstage.io/techdocs-ref: dir:.
    jenkins.io/github-folder: 'deodato/https-github.com-DoubleDdidi-accenture-poc-svc'
    grafana/tag-selector: demoBackstage
  links:
    - url: https://sonarcloud.io/organizations/deodato/projects
      title: Sonar Dashboard
      icon: sonarqube
    - url: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
      title: API Spec
      icon: code    
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  providesApis:
    - AccenturePoc
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/main/APIs/archive.org/search/1.0.0/openapi.yaml

