apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "accenture-poc-svc"
  annotations:
    sonarqube.org/project-key: poc-backstage-svc
spec:
  type: service
  owner: user:guest
  lifecycle: experimental

