apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "accenture-poc-svc"
  description: "accenture poc"
  tags:
    - java
    - node
  annotations:
    sonarqube.org/project-key: poc-backstage-svc
  links:
    - url: http://localhost:9000/dashboard?id=poc-backstage-svc
      title: Sonar Dashboard
      icon: sonarqube
    - url: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
      title: API Spec
      icon: code    
spec:
  type: service
  owner: user:guest
  lifecycle: experimental

